import {
  Plus,
  Pencil,
  Trash2,
  X,
  Download,
  Calendar,
  Clock,
  Banknote,
  CreditCard,
  Tag,
  BarChart3,
  Calculator,
  Repeat,
  Info,
  AlertTriangle,
  Check,
  Target,
  Filter,
  LayoutDashboard,
  Wallet,
  PiggyBank,
  TrendingUp,
  TrendingDown,
  FileText,
  Bell,
  PieChart,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  Sparkles,
  ShieldCheck,
  Zap,
  Globe,
  Lock,
  Search,
  MoreHorizontal,
  ChevronDown,
  ChevronRight,
  Sun,
  Moon,
  Coffee,
  House,
  ShoppingCart,
  Bus,
  Clapperboard,
  HeartPulse,
  Gift,
  Briefcase,
  Rocket,
} from 'lucide-react';

const ICON_MAP = {
  // Legacy names — keep existing call sites working
  add:          Plus,
  edit:         Pencil,
  delete:       Trash2,
  close:        X,
  download:     Download,
  calendar:     Calendar,
  clock:        Clock,
  money:        Banknote,
  card:         CreditCard,
  tag:          Tag,
  chart:        BarChart3,
  calculator:   Calculator,
  repeat:       Repeat,
  info:         Info,
  warning:      AlertTriangle,
  check:        Check,
  target:       Target,
  filter:       Filter,

  // Lucide names
  'layout-dashboard':  LayoutDashboard,
  'chart-pie':         PieChart,
  'chart-bar':         BarChart3,
  'trending-up':       TrendingUp,
  'trending-down':     TrendingDown,
  'file-text':         FileText,
  'arrow-right':       ArrowRight,
  'arrow-up-right':    ArrowUpRight,
  'arrow-down-right':  ArrowDownRight,
  'shield-check':      ShieldCheck,
  'more-horizontal':   MoreHorizontal,
  'chevron-down':      ChevronDown,
  'chevron-right':     ChevronRight,
  'heart-pulse':       HeartPulse,
  'shopping-cart':     ShoppingCart,
  wallet:      Wallet,
  'piggy-bank':PiggyBank,
  banknote:    Banknote,
  sparkles:    Sparkles,
  zap:         Zap,
  globe:       Globe,
  lock:        Lock,
  plus:        Plus,
  search:      Search,
  sun:         Sun,
  moon:        Moon,
  bell:        Bell,
  coffee:      Coffee,
  house:       House,
  bus:         Bus,
  clapperboard:Clapperboard,
  gift:        Gift,
  briefcase:   Briefcase,
  rocket:      Rocket,
  x:           X,
};

export default function Icon({ name, className = 'w-5 h-5', strokeWidth = 1.75, ...props }) {
  const LucideIcon = ICON_MAP[name];

  if (!LucideIcon) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return <LucideIcon className={className} strokeWidth={strokeWidth} {...props} />;
}
